### ISSUE TITLE
2.0.5 introduces dependency on `packaging`, but does not state this in the metadata

### ISSUE THREAD

**Issue by mwchase** [snok/flake8-type-checking#111]
https://github.com/snok/flake8-type-checking/commit/cd0d850953b798624a8c1ceb426802bcb8d25ff4 Adds `from packaging.version import Version`. Running flake8-type-checking against my code, without installing `packaging` leads to:
```
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/home/maxchase/.pyenv/versions/3.9.4/lib/python3.9/importlib/metadata.py", line 77,in load
    module = import_module(match.group('module'))
  File "/home/maxchase/.pyenv/versions/3.9.4/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/path/to/venv/lib/python3.9/site-packages/flake8_type_checking/plugin.py", line 8, in <module>
    from flake8_type_checking.checker import TypingOnlyImportsChecker
  File "/path/to/venv/lib/python3.9/site-packages/flake8_type_checking/checker.py", line 13, in <module>
    from flake8_type_checking.constants import (
  File "/path/to/venv/lib/python3.9/site-packages/flake8_type_checking/constants.py", line 4, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/path/to/venv/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/path/to/venv/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/path/to/venv/lib/python3.9/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/path/to/venv/lib/python3.9/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/path/to/venv/lib/python3.9/site-packages/flake8/main/application.py", line 163, in find_plugins
    self.check_plugins.load_plugins()
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/path/to/venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "TC" due to No module named 'packaging'.
```
When I add `packaging` to my requirements next to `flake8-type-checking`, it works fine.

**Comment by sondrelg** [comment]
Oh wow, I was convinced packaging was builtin 🤦 I'll fix this shortly. Thanks @mwchase 👏

**Comment by sondrelg** [comment]
Could you please test with 2.0.6 @mwchase? Should be live in < 1 min

**Comment by sondrelg** [comment]
Thanks for the quick report. Have added a bunch of additional checks to CI last few days to avoid this happening again, knock on wood 🤞 😄
